name: aaram_bd
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  badges: ^3.1.2
  english_words: ^4.0.0
  provider: ^6.0.0
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.6
  introduction_screen: ^3.1.12
  sms_otp_auto_verify: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.3
  fan_carousel_image_slider: ^1.0.0
  flutter_rating_bar: ^4.0.1
  http: ^1.2.1
  floating_text: ^0.2.0
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.0.6
  dropdown_search: ^6.0.1
  image_picker: ^1.1.2
  readmore: ^3.0.0
  url_launcher: ^6.1.7
  intl: ^0.19.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
